apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13
        env:
        - name: POSTGRES_DB
          value: devops_db
        - name: POSTGRES_USER
          value: amarjeet
        - name: POSTGRES_PASSWORD
          value: password123
---
apiVersion: v1
kind: Service
metadata:
  name: db  # Ye name important hai, backend isi se connect karega
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432